package:
  name: pygenes
  version: "0.0.5"

source:
  git_url: git://github.com/shahcompbio/pygenes.git
  git_rev: v0.0.5

build:
  number: 2

requirements:
  build:
    - python

  run:
    - python

test:
  requires:
    - nose

about:
  home: https://github.com/shahcompbio/pygenes
  license: MIT
  summary: 'In memory gene database searchable using an interval tree'


